export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_CURRENT_USER_INFO = 'ADD_USER_INFO';
export const DELETE_CURRENT_USER_INFO = 'DELETE_CURRENT_USER_INFO';
export const SET_CURRENT_USER_INFO_FROM_LOCALSTORAGE = 'SET_CURRENT_USER_INFO_FROM_LOCALSTORAGE';
export const ADD_CHAT_ROOM = 'ADD_CHAT_ROOM';
