export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_CURRENT_USER_INFO = 'ADD_USER_INFO';
export const DELETE_CURRENT_USER_INFO = 'DELETE_CURRENT_USER_INFO'
export const SET_CURRENT_USER_INFO_FROM_LOCALSTORAGE = 'SET_CURRENT_USER_INFO_FROM_LOCALSTORAGE'